#!/usr/bin/env python3
"""Turn an arbitrary binary asset into a C byte array."""

import argparse
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--name", required=True)
    args = parser.parse_args()

    data = args.input.read_bytes()
    body = "".join(
        ("\n   " if index % 16 == 0 else "") + f" 0x{byte:02X},"
        for index, byte in enumerate(data))
    args.out.write_text(
        "/* Generated by tools/embed_binary.py -- do not edit. */\n"
        f"const unsigned char {args.name}_data[] = {{{body}\n}};\n"
        f"const unsigned {args.name}_size = {len(data)}u;\n")
    print(f"embed_binary: embedded {args.input} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
