#!/usr/bin/env python3
"""Turn the complete UI font into a C source file the executable links in.

The pairing overlay currently draws only digits and a hyphen, but later UI such
as custom-song metadata needs the rest of the face. Keep every glyph so build
results do not depend on whether the host happens to have fontTools installed.

The font itself is never committed -- this runs at configure time against the
local copy in fonts/ (or --font), and CMake simply skips the embed when that
file is absent.

    python3 tools/embed_font.py --font fonts/font.ttf --out build/overlay_font.c
"""

import argparse


def emit(data: bytes, path: str, name: str) -> None:
    body = "".join(
        ("\n   " if i % 16 == 0 else "") + f" 0x{b:02X},"
        for i, b in enumerate(data))
    with open(path, "w") as f:
        f.write(
            f"/* Generated by tools/embed_font.py -- do not edit. */\n"
            f"const unsigned char {name}_data[] = {{{body}\n}};\n"
            f"const unsigned {name}_size = {len(data)}u;\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--name", default="taiko_overlay_font")
    args = ap.parse_args()

    with open(args.font, "rb") as f:
        data = f.read()
    emit(data, args.out, args.name)
    print(f"embed_font: embedded complete font ({len(data)} bytes)")


if __name__ == "__main__":
    main()
