#!/usr/bin/env python3
"""Generate the SPU workload registration file for this title.

ps3recomp's SPU strategy is static lifting: each SPU ELF the game hands to
cellSpurs is lifted ahead of time (tools/spu_lifter.py) into a native entry
function, and the runtime maps a guest image to its lifted entry by
FNV-1a-64 fingerprint over the exact ELF bytes.

This emits the glue that registers Taiko's images at startup. Run after
re-lifting:

    python3 tools/gen_spu_workloads.py

Adapted from ps3recomp/tools/gen_spu_workloads.py, which hardcodes another
title's paths and symbol names.
"""

import glob
import os
import pathlib

REPO = pathlib.Path(__file__).resolve().parent.parent
SPU_DIR = REPO / "game" / "spu"
OUT = REPO / "src" / "spu_gen" / "taiko_spu_workloads.c"


def be16(b, o):
    return (b[o] << 8) | b[o + 1]


def be32(b, o):
    return (b[o] << 24) | (b[o + 1] << 16) | (b[o + 2] << 8) | b[o + 3]


def img_size(b):
    """Bytes of the ELF the game actually hands to cellSpurs -- the fingerprint
    must cover exactly this range, identically to the runtime's computation."""
    e_phoff, e_shoff = be32(b, 0x1C), be32(b, 0x20)
    e_phentsize, e_phnum = be16(b, 0x2A), be16(b, 0x2C)
    e_shentsize, e_shnum = be16(b, 0x2E), be16(b, 0x30)
    end = e_shoff + e_shnum * e_shentsize
    for k in range(e_phnum):
        po = e_phoff + k * e_phentsize
        if po + 0x14 > len(b):
            break
        end = max(end, be32(b, po + 0x04) + be32(b, po + 0x10))
    for k in range(e_shnum):
        so = e_shoff + k * e_shentsize
        if so + 0x18 > len(b):
            break
        if be32(b, so + 0x04) != 8:            # not SHT_NOBITS
            end = max(end, be32(b, so + 0x10) + be32(b, so + 0x14))
    return min(end, len(b))


def fnv1a64(b):
    h = 1469598103934665603
    for x in b:
        h = ((h ^ x) * 1099511628211) & 0xFFFFFFFFFFFFFFFF
    return h


def main():
    files = sorted(glob.glob(str(SPU_DIR / "*.elf")))
    if not files:
        raise SystemExit("no SPU images in %s -- run extract_spu_images.py" % SPU_DIR)

    imgs = []
    for f in files:
        name = os.path.splitext(os.path.basename(f))[0]
        b = open(f, "rb").read()
        imgs.append((name, fnv1a64(b[: img_size(b)]), be32(b, 0x18)))

    L = []
    L.append("/* taiko_spu_workloads.c -- GENERATED by tools/gen_spu_workloads.py.")
    L.append(" *")
    L.append(" * Registers the title's %d lifted SPU images with the workload dispatch"
             % len(imgs))
    L.append(" * registry (keyed by FNV-1a-64 fingerprint of the ELF bytes) and populates")
    L.append(" * each image's indirect-branch table under a distinct image id.")
    L.append(" * cellSpursAddWorkload / cellSpursCreateTask call spu_workload_dispatch(),")
    L.append(" * which fingerprints the guest image, finds the lifted entry here, and runs")
    L.append(" * it on a fresh 256 KB local store.")
    L.append(" *")
    L.append(" * Do not edit; re-run the generator instead. */")
    L.append('#include "../../ps3recomp/runtime/spu/spu_workload.h"')
    L.append("")
    L.append("extern void spu_begin_image(int image_id);")
    L.append("")
    for name, fp, ent in imgs:
        L.append("extern void %s_spu_func_%08X(spu_context*);" % (name, ent))
        L.append("extern void %s_spu_recomp_register(void);" % name)
    L.append("")
    L.append("void taiko_spu_register_all(void)")
    L.append("{")
    for i, (name, fp, ent) in enumerate(imgs, 1):
        L.append("    spu_begin_image(%d); %s_spu_recomp_register();" % (i, name))
        L.append("    spu_workload_register_img(0x%016XULL, %s_spu_func_%08X, %d, \"%s\");"
                 % (fp, name, ent, i, name))
    L.append("    spu_begin_image(0);")
    L.append("}")
    L.append("")
    L.append("/* Register before the game adds any SPURS workload or task. */")
    L.append("__attribute__((constructor)) static void taiko_spu_autoreg(void)")
    L.append("{")
    L.append("    taiko_spu_register_all();")
    L.append("}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n")
    print("Wrote %s with %d images:" % (OUT, len(imgs)))
    for name, fp, ent in imgs:
        print("  %-28s entry=0x%08X fp=0x%016X" % (name, ent, fp))


if __name__ == "__main__":
    main()
