#!/usr/bin/env python3
"""Bake assets/ui/pairing_pill.png into a C array.

The overlay has no PNG decoder and does not want one for a single 272x64
asset, so the pixels are embedded. Re-run this after editing the artwork:

    python3 tools/gen_pairing_pill.py
"""
import pathlib
import sys

from PIL import Image

root = pathlib.Path(__file__).resolve().parent.parent
source = root / "assets/ui/pairing_pill.png"
target = root / "src/taiko_pairing_pill.h"

image = Image.open(source).convert("RGBA")
pixels = image.tobytes()

lines = [
    "/* Generated by tools/gen_pairing_pill.py from assets/ui/pairing_pill.png.",
    " * Do not edit: change the artwork and re-run the generator. */",
    "#ifndef TAIKO_PAIRING_PILL_H",
    "#define TAIKO_PAIRING_PILL_H",
    "",
    f"#define TAIKO_PAIRING_PILL_WIDTH  {image.width}",
    f"#define TAIKO_PAIRING_PILL_HEIGHT {image.height}",
    "",
    "static const unsigned char taiko_pairing_pill_rgba[] = {",
]
for offset in range(0, len(pixels), 16):
    chunk = ", ".join(f"0x{b:02X}" for b in pixels[offset:offset + 16])
    lines.append(f"    {chunk},")
lines += ["};", "", "#endif /* TAIKO_PAIRING_PILL_H */", ""]

target.write_text("\n".join(lines))
print(f"{source.name}: {image.width}x{image.height} -> {target.relative_to(root)}"
      f" ({len(pixels)} bytes)", file=sys.stderr)
