/* See taiko_overlay.h.
 *
 * The styling follows TaikoZucchini's core/title_render.c (MIT, same author):
 * white fill, and the outline built by disk-dilating the glyph's own coverage
 * mask rather than by stroking the outline, which is what gives the title's
 * text its rounded, even border. Only the parts a six-digit code needs are
 * here -- no title cache, no vertical text, no per-song prerender.
 */
#include "taiko_overlay.h"

#include <math.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include <ft2build.h>
#include FT_FREETYPE_H

#include "taiko_pairing_pill.h"

/* The artwork sets the layout: a red disc on the left for the countdown, a
 * yellow body for the code. Both texts are black, as on the cabinet. */
enum {
    PILL_WIDTH = TAIKO_PAIRING_PILL_WIDTH,
    PILL_HEIGHT = TAIKO_PAIRING_PILL_HEIGHT,
    HOST_WIDTH = 1280,
    HOST_HEIGHT = 720,
    OVERLAY_MAX_WIDTH = HOST_WIDTH,
    OVERLAY_MAX_HEIGHT = HOST_HEIGHT,
    PILL_DISC_WIDTH = 64,             /* the red disc at the left end */
    CODE_CENTER_X = 158,
    CODE_PIXELS = 34,
    COUNTDOWN_PIXELS = 26,
};

static const uint32_t COLOR_TEXT = 0xFFFFFFFFu;      /* fill */
static const uint32_t COLOR_TEXT_OUTLINE = 0xFF000000u;
#define RGB_COLOUR(red, green, blue) \
    (0xFF000000u | ((uint32_t)(blue) << 16) | \
     ((uint32_t)(green) << 8) | (uint32_t)(red))
enum { TEXT_OUTLINE_RADIUS = 3 };

static pthread_mutex_t g_lock = PTHREAD_MUTEX_INITIALIZER;
static uint32_t g_pixels[OVERLAY_MAX_WIDTH * OVERLAY_MAX_HEIGHT];
static uint32_t g_version;
static int      g_visible;
static int      g_mode;             /* 1 pairing, 2 status, 3--5 host screens */
static int      g_width = PILL_WIDTH;
static int      g_height = PILL_HEIGHT;
static int      g_host_selection;
static char     g_code[16];
static char     g_status[32];
static char     g_player_name[64];
static char     g_song_id[32];
static char     g_song_title[256];
static char     g_song_genre[128];
static char     g_song_difficulty[32];
static char     g_song_query[128];
static uint32_t g_song_unique_id;
static unsigned g_song_index;
static unsigned g_song_match_total;
static unsigned g_song_catalog_total;
static char     g_song_category[64];
static unsigned g_song_category_index;
static unsigned g_song_category_total;
static uint8_t  g_song_difficulty_mask;
static int      g_song_search_active;
static int      g_song_browser_level;
static int      g_song_selection_is_exit;
typedef struct song_row_storage {
    char title[256];
    char genre[128];
    unsigned catalog_index;
    int selected;
    int kind;
} song_row_storage;
static song_row_storage g_song_rows[TAIKO_OVERLAY_SONG_ROW_COUNT];
static unsigned g_song_row_count;
static long     g_deadline;
static int      g_drawn_remaining = -1;

static FT_Library g_library;
static FT_Face    g_face;
static int        g_font_state;    /* 0 untried, 1 ready, -1 unavailable */

/* Published to the RSX backend, which blits whatever this returns over the
 * frame. Weak so a build with a backend that has no overlay support still
 * links; the assignment below is then simply skipped. */
extern const uint32_t* (*g_rsx_overlay_frame)(int* width, int* height,
                                              uint32_t* version)
    __attribute__((weak));

__attribute__((constructor))
static void taiko_overlay_register(void)
{
    if (&g_rsx_overlay_frame) g_rsx_overlay_frame = taiko_overlay_frame;
}

static long monotonic_seconds(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long)ts.tv_sec;
}

#ifdef TAIKO_OVERLAY_FONT_EMBEDDED
/* Generated by tools/embed_font.py at configure time: the digits and hyphen of
 * the game font, so the executable needs no font file beside it. */
extern const unsigned char taiko_overlay_font_data[];
extern const unsigned taiko_overlay_font_size;
#endif

static int font_ready(void)
{
    if (g_font_state) return g_font_state > 0;
    g_font_state = -1;

    if (FT_Init_FreeType(&g_library) != 0) return 0;

    /* An explicit TAIKO_OVERLAY_FONT always wins, so a different face can be
     * tried without rebuilding. */
    const char* path = getenv("TAIKO_OVERLAY_FONT");
#ifdef TAIKO_OVERLAY_FONT_EMBEDDED
    if (!path || !path[0]) {
        if (FT_New_Memory_Face(g_library, taiko_overlay_font_data,
                               (FT_Long)taiko_overlay_font_size, 0,
                               &g_face) != 0) {
            fprintf(stderr, "[taiko_overlay] embedded font is unusable\n");
            return 0;
        }
        g_font_state = 1;
        fprintf(stderr, "[taiko_overlay] font embedded, %u bytes (%s)\n",
                taiko_overlay_font_size,
                g_face->family_name ? g_face->family_name : "?");
        return 1;
    }
#endif
    if (!path || !path[0]) path = "fonts/font.ttf";
    if (FT_New_Face(g_library, path, 0, &g_face) != 0) {
        fprintf(stderr, "[taiko_overlay] no font at '%s'; "
                        "set TAIKO_OVERLAY_FONT to the game font\n", path);
        return 0;
    }
    g_font_state = 1;
    fprintf(stderr, "[taiko_overlay] font '%s' (%s)\n", path,
            g_face->family_name ? g_face->family_name : "?");
    return 1;
}

/* --------------------------------------------------------------------------
 * Drawing
 * -----------------------------------------------------------------------*/

/* Alpha-composite one coverage sample. The overlay keeps its own alpha so the
 * pill's rounded ends stay transparent on screen. */
static void put_pixel(int x, int y, uint32_t colour, unsigned coverage)
{
    if (x < 0 || y < 0 || x >= g_width || y >= g_height || !coverage)
        return;

    uint32_t* target = &g_pixels[(size_t)y * g_width + x];
    const unsigned source_alpha = ((colour >> 24) & 0xFF) * coverage / 255u;
    if (!source_alpha) return;

    const unsigned destination_alpha = (*target >> 24) & 0xFF;
    const unsigned destination_weight =
        (destination_alpha * (255u - source_alpha) + 127u) / 255u;
    const unsigned out_alpha = source_alpha + destination_weight;
    if (!out_alpha) return;

    uint32_t out = out_alpha << 24;
    for (int shift = 0; shift < 24; shift += 8) {
        const unsigned src = (colour >> shift) & 0xFF;
        const unsigned dst = (*target >> shift) & 0xFF;
        out |= (((src * source_alpha + dst * destination_weight + out_alpha / 2u) /
                 out_alpha) & 0xFFu) << shift;
    }
    *target = out;
}

static void draw_pill(void)
{
    g_width = PILL_WIDTH;
    g_height = PILL_HEIGHT;
    for (int i = 0; i < PILL_WIDTH * PILL_HEIGHT; i++) {
        const unsigned char* pixel = &taiko_pairing_pill_rgba[i * 4];
        g_pixels[i] = ((uint32_t)pixel[3] << 24) | ((uint32_t)pixel[2] << 16) |
                      ((uint32_t)pixel[1] << 8) | (uint32_t)pixel[0];
    }
}

/* The outline is the glyph's own coverage grown into a disc, which is what
 * keeps the border even around the font's rounded strokes. */
static void draw_glyph(const FT_Bitmap* bitmap, int origin_x, int origin_y,
                       int outline)
{
    for (unsigned row = 0; row < bitmap->rows; row++) {
        for (unsigned column = 0; column < bitmap->width; column++) {
            const unsigned coverage =
                bitmap->buffer[row * (unsigned)bitmap->pitch + column];
            if (!coverage) continue;
            const int px = origin_x + (int)column;
            const int py = origin_y + (int)row;
            if (!outline) {
                put_pixel(px, py, COLOR_TEXT, coverage);
                continue;
            }
            for (int dy = -TEXT_OUTLINE_RADIUS; dy <= TEXT_OUTLINE_RADIUS; dy++)
                for (int dx = -TEXT_OUTLINE_RADIUS; dx <= TEXT_OUTLINE_RADIUS; dx++)
                    if (dx * dx + dy * dy <= TEXT_OUTLINE_RADIUS * TEXT_OUTLINE_RADIUS)
                        put_pixel(px + dx, py + dy, COLOR_TEXT_OUTLINE, coverage);
        }
    }
}

static int text_width(const char* text, int pixels)
{
    int width = 0;
    if (FT_Set_Pixel_Sizes(g_face, 0, (FT_UInt)pixels) != 0) return 0;
    const unsigned char* cursor = (const unsigned char*)text;
    while (*cursor) {
        FT_ULong codepoint = *cursor++;
        if ((codepoint & 0xE0u) == 0xC0u && (cursor[0] & 0xC0u) == 0x80u) {
            codepoint = ((codepoint & 0x1Fu) << 6) | (cursor[0] & 0x3Fu);
            cursor += 1;
        } else if ((codepoint & 0xF0u) == 0xE0u &&
                   (cursor[0] & 0xC0u) == 0x80u &&
                   (cursor[1] & 0xC0u) == 0x80u) {
            codepoint = ((codepoint & 0x0Fu) << 12) |
                        ((cursor[0] & 0x3Fu) << 6) | (cursor[1] & 0x3Fu);
            cursor += 2;
        } else if ((codepoint & 0xF8u) == 0xF0u &&
                   (cursor[0] & 0xC0u) == 0x80u &&
                   (cursor[1] & 0xC0u) == 0x80u &&
                   (cursor[2] & 0xC0u) == 0x80u) {
            codepoint = ((codepoint & 0x07u) << 18) |
                        ((cursor[0] & 0x3Fu) << 12) |
                        ((cursor[1] & 0x3Fu) << 6) | (cursor[2] & 0x3Fu);
            cursor += 3;
        }
        if (FT_Load_Char(g_face, codepoint, FT_LOAD_DEFAULT) != 0)
            continue;
        width += (int)(g_face->glyph->advance.x >> 6);
    }
    return width;
}

/* Centred on `centre_x`, and vertically centred on the pill rather than sat on
 * a baseline: the strings here are digits and a hyphen, so their ink box is
 * what should look centred. */
static void draw_text_at(const char* text, int pixels, int centre_x, int centre_y)
{
    if (FT_Set_Pixel_Sizes(g_face, 0, (FT_UInt)pixels) != 0) return;

    int top = g_height, bottom = 0;
    const unsigned char* cursor = (const unsigned char*)text;
    while (*cursor) {
        FT_ULong codepoint = *cursor++;
        if ((codepoint & 0xE0u) == 0xC0u && (cursor[0] & 0xC0u) == 0x80u) {
            codepoint = ((codepoint & 0x1Fu) << 6) | (cursor[0] & 0x3Fu);
            cursor += 1;
        } else if ((codepoint & 0xF0u) == 0xE0u &&
                   (cursor[0] & 0xC0u) == 0x80u &&
                   (cursor[1] & 0xC0u) == 0x80u) {
            codepoint = ((codepoint & 0x0Fu) << 12) |
                        ((cursor[0] & 0x3Fu) << 6) | (cursor[1] & 0x3Fu);
            cursor += 2;
        } else if ((codepoint & 0xF8u) == 0xF0u &&
                   (cursor[0] & 0xC0u) == 0x80u &&
                   (cursor[1] & 0xC0u) == 0x80u &&
                   (cursor[2] & 0xC0u) == 0x80u) {
            codepoint = ((codepoint & 0x07u) << 18) |
                        ((cursor[0] & 0x3Fu) << 12) |
                        ((cursor[1] & 0x3Fu) << 6) | (cursor[2] & 0x3Fu);
            cursor += 3;
        }
        if (FT_Load_Char(g_face, codepoint, FT_LOAD_DEFAULT) != 0)
            continue;
        const FT_Glyph_Metrics* metrics = &g_face->glyph->metrics;
        const int glyph_top = (int)(metrics->horiBearingY >> 6);
        const int glyph_bottom = glyph_top - (int)(metrics->height >> 6);
        if (glyph_top > bottom) bottom = glyph_top;
        if (glyph_bottom < top) top = glyph_bottom;
    }
    const int baseline = centre_y + (bottom + top) / 2;

    /* Two passes, so every outline stays behind every fill. */
    for (int pass = 0; pass < 2; pass++) {
        int pen_x = centre_x - text_width(text, pixels) / 2;
        if (FT_Set_Pixel_Sizes(g_face, 0, (FT_UInt)pixels) != 0) return;
        cursor = (const unsigned char*)text;
        while (*cursor) {
            FT_ULong codepoint = *cursor++;
            if ((codepoint & 0xE0u) == 0xC0u &&
                (cursor[0] & 0xC0u) == 0x80u) {
                codepoint = ((codepoint & 0x1Fu) << 6) | (cursor[0] & 0x3Fu);
                cursor += 1;
            } else if ((codepoint & 0xF0u) == 0xE0u &&
                       (cursor[0] & 0xC0u) == 0x80u &&
                       (cursor[1] & 0xC0u) == 0x80u) {
                codepoint = ((codepoint & 0x0Fu) << 12) |
                            ((cursor[0] & 0x3Fu) << 6) | (cursor[1] & 0x3Fu);
                cursor += 2;
            } else if ((codepoint & 0xF8u) == 0xF0u &&
                       (cursor[0] & 0xC0u) == 0x80u &&
                       (cursor[1] & 0xC0u) == 0x80u &&
                       (cursor[2] & 0xC0u) == 0x80u) {
                codepoint = ((codepoint & 0x07u) << 18) |
                            ((cursor[0] & 0x3Fu) << 12) |
                            ((cursor[1] & 0x3Fu) << 6) | (cursor[2] & 0x3Fu);
                cursor += 3;
            }
            if (FT_Load_Char(g_face, codepoint, FT_LOAD_RENDER) != 0)
                continue;
            const FT_GlyphSlot glyph = g_face->glyph;
            draw_glyph(&glyph->bitmap, pen_x + glyph->bitmap_left,
                       baseline - glyph->bitmap_top, pass == 0);
            pen_x += (int)(glyph->advance.x >> 6);
        }
    }
}

static void draw_text_fit(const char* text, int preferred_pixels,
                          int maximum_width, int centre_x, int centre_y)
{
    int pixels = preferred_pixels;
    while (pixels > 20 && text_width(text, pixels) > maximum_width)
        pixels -= 2;
    draw_text_at(text, pixels, centre_x, centre_y);
}

static void draw_text_left_fit(const char* text, int preferred_pixels,
                               int maximum_width, int left, int centre_y)
{
    int pixels = preferred_pixels;
    while (pixels > 15 && text_width(text, pixels) > maximum_width)
        pixels -= 2;
    draw_text_at(text, pixels, left + text_width(text, pixels) / 2,
                 centre_y);
}

static void draw_text_right(const char* text, int pixels, int right,
                            int centre_y)
{
    draw_text_at(text, pixels, right - text_width(text, pixels) / 2,
                 centre_y);
}

static void fill_rect(int left, int top, int right, int bottom, uint32_t colour)
{
    if (left < 0) left = 0;
    if (top < 0) top = 0;
    if (right > g_width) right = g_width;
    if (bottom > g_height) bottom = g_height;
    for (int y = top; y < bottom; ++y)
        for (int x = left; x < right; ++x)
            g_pixels[(size_t)y * g_width + x] = colour;
}

static void fill_rounded_rect(int left, int top, int right, int bottom,
                              int radius, uint32_t colour)
{
    if (radius <= 0) {
        fill_rect(left, top, right, bottom, colour);
        return;
    }
    fill_rect(left + radius, top, right - radius, bottom, colour);
    fill_rect(left, top + radius, right, bottom - radius, colour);
    const int radius_squared = radius * radius;
    for (int y = 0; y < radius; ++y) {
        for (int x = 0; x < radius; ++x) {
            const int dx = radius - x - 1;
            const int dy = radius - y - 1;
            if (dx * dx + dy * dy > radius_squared) continue;
            put_pixel(left + x, top + y, colour, 255);
            put_pixel(right - x - 1, top + y, colour, 255);
            put_pixel(left + x, bottom - y - 1, colour, 255);
            put_pixel(right - x - 1, bottom - y - 1, colour, 255);
        }
    }
}

static uint32_t genre_colour(const char* genre)
{
    static const uint32_t palette[] = {
        RGB_COLOUR(0xF0, 0x6A, 0x9B), RGB_COLOUR(0x6B, 0xC6, 0xE8),
        RGB_COLOUR(0x9B, 0x7B, 0xE8), RGB_COLOUR(0x62, 0xC7, 0xA5),
        RGB_COLOUR(0xF2, 0x9D, 0x50), RGB_COLOUR(0xDF, 0x6B, 0x6B),
        RGB_COLOUR(0x78, 0xA7, 0xF2),
    };
    uint32_t hash = 2166136261u;
    for (const unsigned char* cursor = (const unsigned char*)genre;
         cursor && *cursor; ++cursor) {
        hash ^= *cursor;
        hash *= 16777619u;
    }
    return palette[hash % (sizeof(palette) / sizeof(palette[0]))];
}

static void render_host(void)
{
    g_width = HOST_WIDTH;
    g_height = HOST_HEIGHT;
    fill_rect(0, 0, g_width, g_height, 0xFF24170Fu);
    fill_rect(0, 0, g_width, 150, 0xFF5A2415u);
    fill_rect(0, 145, g_width, 150, 0xFF40C8FFu);

    if (g_mode == 3) {
        draw_text_at("PLAYER LOGIN", 58, HOST_WIDTH / 2, 82);
        const uint32_t selected = 0xFF36B7F3u;
        const uint32_t idle = 0xFF574232u;
        fill_rect(185, 235, 615, 455, g_host_selection == 0 ? selected : idle);
        fill_rect(665, 235, 1095, 455, g_host_selection == 1 ? selected : idle);
        draw_text_at("ANONYMOUS", 42, 400, 330);
        draw_text_at("NO CARD - OFFLINE", 25, 400, 392);
        draw_text_at("BANAPASSPORT", 42, 880, 330);
        draw_text_at("USE YOUR SAVED PROFILE", 25, 880, 392);
        draw_text_at("RIM: CHOOSE     CENTRE: CONFIRM", 29,
                     HOST_WIDTH / 2, 580);
        return;
    }

    if (g_mode == 4) {
        draw_text_at("BANAPASSPORT LOGIN", 54, HOST_WIDTH / 2, 82);
        draw_text_at("ENTER THIS CODE ON THE PAIRING PAGE", 31,
                     HOST_WIDTH / 2, 245);
        if (g_code[0]) {
            char code[16];
            if (strlen(g_code) == 6)
                snprintf(code, sizeof(code), "%.3s-%s", g_code, g_code + 3);
            else
                snprintf(code, sizeof(code), "%s", g_code);
            draw_text_at(code, 88, HOST_WIDTH / 2, 365);
            char countdown[48];
            int remaining = (int)(g_deadline - monotonic_seconds());
            if (remaining < 0) remaining = 0;
            snprintf(countdown, sizeof(countdown), "EXPIRES IN %d", remaining);
            draw_text_at(countdown, 29, HOST_WIDTH / 2, 465);
        } else {
            draw_text_at("WAITING FOR SERVER...", 46, HOST_WIDTH / 2, 365);
        }
        draw_text_at("THE GAME IS AUTHENTICATING THROUGH ITS NATIVE CARD PATH",
                     24, HOST_WIDTH / 2, 580);
        return;
    }

    if (g_mode == 6) {
        draw_text_at("STARTING SESSION", 58, HOST_WIDTH / 2, 82);
        if (g_player_name[0])
            draw_text_at(g_player_name, 40, HOST_WIDTH / 2, 315);
        draw_text_at("PLAYER DATA IS READY", 34, HOST_WIDTH / 2, 400);
        draw_text_at("FINISHING THE NATIVE GAME HANDOFF...", 27,
                     HOST_WIDTH / 2, 535);
        return;
    }

    /* Song Select borrows osu!lazer's high-level composition: persistent
     * details on the left, search above a dense right-side carousel, and the
     * selected card pulled toward the centre. It stays deliberately static --
     * this surface is CPU-rasterized only when input changes. */
    fill_rect(0, 0, g_width, g_height, RGB_COLOUR(0x10, 0x18, 0x25));
    fill_rect(0, 0, 570, 660, RGB_COLOUR(0x19, 0x28, 0x3A));
    fill_rect(570, 0, g_width, 660, RGB_COLOUR(0x11, 0x1B, 0x29));
    fill_rect(0, 0, 570, 7, RGB_COLOUR(0xF0, 0x6A, 0x9B));
    fill_rect(570, 0, g_width, 7, RGB_COLOUR(0x6B, 0xC6, 0xE8));
    for (int y = 0; y < 660; y += 80)
        fill_rect(570, y, g_width, y + 1, RGB_COLOUR(0x1D, 0x2A, 0x3A));

    draw_text_left_fit(g_song_browser_level == TAIKO_OVERLAY_BROWSER_CATEGORIES
                           ? "CATEGORY SELECT" : "SONG SELECT",
                       39, 440, 34, 49);
    draw_text_left_fit("TAIKO GREEN / HOST LIBRARY", 17, 480, 35, 82);
    char category[112];
    if (g_song_browser_level == TAIKO_OVERLAY_BROWSER_CATEGORIES)
        snprintf(category, sizeof(category), "CHOOSE A GENRE FOLDER");
    else if (!g_song_category_total)
        snprintf(category, sizeof(category), "[ SEARCH RESULTS ]");
    else
        snprintf(category, sizeof(category), "[ %s ]  FOLDER %u/%u",
                 g_song_category[0] ? g_song_category : "SONGS",
                 g_song_category_index + 1, g_song_category_total);
    draw_text_left_fit(category, 17, 370, 35, 108);
    draw_text_right(g_player_name, 13, 535, 108);

    fill_rounded_rect(625, 24, 1248, 91, 12,
                      g_song_search_active
                          ? RGB_COLOUR(0x35, 0x5D, 0x78)
                          : RGB_COLOUR(0x25, 0x37, 0x4A));
    fill_rect(625, 87, 1248, 91,
              g_song_search_active
                  ? RGB_COLOUR(0xF0, 0x6A, 0x9B)
                  : RGB_COLOUR(0x6B, 0xC6, 0xE8));
    char search[192];
    if (g_song_browser_level == TAIKO_OVERLAY_BROWSER_CATEGORIES)
        snprintf(search, sizeof(search),
                 "TAB / CTRL+F  SEARCH ALL SONGS");
    else if (g_song_query[0])
        snprintf(search, sizeof(search), "SEARCH: %s%s", g_song_query,
                 g_song_search_active ? "_" : "");
    else
        snprintf(search, sizeof(search), "%s",
                 g_song_search_active ? "TYPE TO FILTER..._"
                                      : "TAB / CTRL+F TO SEARCH");
    draw_text_left_fit(search, 23, 390, 648, 56);
    char result_count[80];
    if (g_song_browser_level == TAIKO_OVERLAY_BROWSER_CATEGORIES)
        snprintf(result_count, sizeof(result_count), "%u CATEGORIES",
                 g_song_match_total);
    else
        snprintf(result_count, sizeof(result_count), "%u SONGS",
                 g_song_match_total);
    draw_text_right(result_count, 18, 1224, 58);

    if (!g_song_catalog_total) {
        draw_text_at("CATALOG UNAVAILABLE", 42, 900, 320);
        draw_text_at("CHECK PS3_VFS_ROOT AND MUSICINFO.XML", 23, 900, 375);
        return;
    }

    if (!g_song_match_total &&
        g_song_browser_level == TAIKO_OVERLAY_BROWSER_SONGS) {
        draw_text_at("NO MATCHES", 43, 910, 313);
        draw_text_at("BACKSPACE TO EDIT OR ESC TO CLEAR", 22, 910, 369);
    } else {
        fill_rounded_rect(28, 125, 537, 379, 14,
                          RGB_COLOUR(0x23, 0x37, 0x4B));
        fill_rect(28, 125, 36, 379,
                  genre_colour(g_song_browser_level ==
                                       TAIKO_OVERLAY_BROWSER_CATEGORIES
                                   ? g_song_title : g_song_genre));
        if (g_song_browser_level == TAIKO_OVERLAY_BROWSER_CATEGORIES) {
            draw_text_left_fit(g_song_title, 47, 445, 57, 205);
            char folder_count[80];
            snprintf(folder_count, sizeof(folder_count), "%u SONGS",
                     g_song_unique_id);
            draw_text_left_fit(folder_count, 26, 450, 57, 292);
            draw_text_left_fit("ENTER OR RIGHT CENTRE  OPEN", 19, 490,
                               34, 455);
            draw_text_left_fit("RIM / WHEEL  CHOOSE CATEGORY", 17, 490,
                               34, 495);
        } else if (g_song_selection_is_exit) {
            draw_text_left_fit(g_song_genre, 21, 450, 57, 160);
            draw_text_left_fit("BACK TO CATEGORIES", 39, 445, 57, 225);
            draw_text_left_fit("RETURN TO THE FOLDER LIST", 21, 450,
                               57, 303);
            draw_text_left_fit("ENTER OR RIGHT CENTRE  EXIT", 19, 490,
                               34, 455);
        } else {
            draw_text_left_fit(g_song_genre[0] ? g_song_genre : "OTHER", 21,
                               450, 57, 160);
            draw_text_left_fit(g_song_title, 41, 445, 57, 225);

            char identity[160];
            snprintf(identity, sizeof(identity), "ID  %s     UNIQUE  %u",
                     g_song_id, g_song_unique_id);
            draw_text_left_fit(identity, 19, 450, 57, 303);
            char position[80];
            snprintf(position, sizeof(position), "SONG %u OF %u",
                     g_song_index + 1, g_song_match_total);
            draw_text_left_fit(position, 19, 450, 57, 345);

            draw_text_left_fit("DIFFICULTY", 21, 460, 34, 420);
            static const char* difficulty_names[] = {
                "EASY", "NORMAL", "HARD", "ONI", "URA"
            };
            for (unsigned difficulty = 0; difficulty < 5; ++difficulty) {
                const int left = 28 + (int)difficulty * 102;
                const int available =
                    (g_song_difficulty_mask & (1u << difficulty)) != 0;
                const int selected = strcmp(
                    g_song_difficulty, difficulty_names[difficulty]) == 0;
                const uint32_t colour = !available
                    ? RGB_COLOUR(0x20, 0x2A, 0x36)
                    : selected ? RGB_COLOUR(0xE6, 0x5B, 0x91)
                               : RGB_COLOUR(0x34, 0x4A, 0x60);
                fill_rounded_rect(left, 446, left + 92, 493, 9, colour);
                draw_text_at(difficulty_names[difficulty], 16,
                             left + 46, 469);
            }

            draw_text_left_fit("LEFT / RIGHT  CHANGE DIFFICULTY", 17, 490,
                               34, 530);
            draw_text_left_fit("ENTER OR RIGHT CENTRE  PLAY", 19, 490,
                               34, 565);
            draw_text_left_fit("R  RANDOM SONG", 17, 490, 34, 600);
        }

        const int first_y = 111;
        const int row_step = 59;
        for (unsigned row = 0; row < g_song_row_count; ++row) {
            const song_row_storage* item = &g_song_rows[row];
            const int top = first_y + (int)row * row_step;
            const int left = item->selected ? 594 : 628;
            const uint32_t colour = item->kind == TAIKO_OVERLAY_ROW_EXIT
                ? (item->selected ? RGB_COLOUR(0xD8, 0x58, 0x70)
                                  : RGB_COLOUR(0x4B, 0x2A, 0x38))
                : item->selected ? genre_colour(item->genre)
                                 : RGB_COLOUR(0x29, 0x3A, 0x4D);
            fill_rounded_rect(left, top, 1252, top + 53, 10, colour);
            if (!item->selected)
                fill_rect(left, top, left + 5, top + 53,
                          genre_colour(item->genre));
            if (item->kind == TAIKO_OVERLAY_ROW_CATEGORY) {
                draw_text_left_fit(item->title, item->selected ? 28 : 25,
                                   item->selected ? 470 : 450,
                                   left + 18, top + 27);
            } else {
                draw_text_left_fit(item->title, item->selected ? 22 : 19,
                                   item->selected ? 470 : 450,
                                   left + 18, top + 19);
                draw_text_left_fit(
                    item->kind == TAIKO_OVERLAY_ROW_EXIT
                        ? "RETURN TO THE CATEGORY LIST" : item->genre,
                    15, 350, left + 19, top + 40);
            }
            char number[24];
            if (item->kind == TAIKO_OVERLAY_ROW_CATEGORY)
                snprintf(number, sizeof(number), "%u SONGS",
                         item->catalog_index);
            else if (item->kind == TAIKO_OVERLAY_ROW_EXIT)
                snprintf(number, sizeof(number), "EXIT");
            else
                snprintf(number, sizeof(number), "%03u",
                         item->catalog_index + 1);
            draw_text_right(number, 17, 1231, top + 27);
        }
    }

    fill_rect(0, 660, g_width, g_height, RGB_COLOUR(0x0B, 0x11, 0x1B));
    draw_text_left_fit("RIM / WHEEL  BROWSE", 18, 290, 30, 690);
    draw_text_at(g_song_browser_level == TAIKO_OVERLAY_BROWSER_CATEGORIES
                     ? "ENTER  OPEN FOLDER"
                     : "UP/DOWN  BROWSE     PAGEUP/DOWN  SKIP",
                 16, 655, 690);
    draw_text_right(g_song_browser_level == TAIKO_OVERLAY_BROWSER_CATEGORIES
                        ? "9 ORIGINAL CATEGORIES"
                        : "ESC  BACK / CLEAR FILTER",
                    17, 1245, 690);
}

static void render(int remaining)
{
    char code[16];
    char countdown[4];

    if (g_mode >= 3) {
        render_host();
        g_drawn_remaining = remaining;
        ++g_version;
        return;
    }

    draw_pill();

    if (g_mode == 2) {
        draw_text_at(g_status, 24, PILL_WIDTH / 2, PILL_HEIGHT / 2);
        g_drawn_remaining = remaining;
        ++g_version;
        return;
    }

    /* 661722 reads as 661-722 on the cabinet. */
    if (strlen(g_code) == 6)
        snprintf(code, sizeof(code), "%.3s-%s", g_code, g_code + 3);
    else
        snprintf(code, sizeof(code), "%s", g_code);
    draw_text_at(code, CODE_PIXELS, CODE_CENTER_X, PILL_HEIGHT / 2);

    snprintf(countdown, sizeof(countdown), "%d", remaining > 99 ? 99 : remaining);
    draw_text_at(countdown, COUNTDOWN_PIXELS, PILL_DISC_WIDTH / 2,
                 PILL_HEIGHT / 2);

    g_drawn_remaining = remaining;
    ++g_version;
}

/* --------------------------------------------------------------------------
 * Public entry points
 * -----------------------------------------------------------------------*/

void taiko_overlay_set_pairing(const char* code, int expires_in)
{
    pthread_mutex_lock(&g_lock);
    /* The reader polls before the user chooses BAID. Its legacy pairing pill
     * must not replace an opaque host-owned screen. Mode 4 is the exception:
     * it is the host BAID screen and consumes the refreshed code itself. */
    if (g_mode >= 3 && g_mode != 4) {
        pthread_mutex_unlock(&g_lock);
        return;
    }
    snprintf(g_code, sizeof(g_code), "%s", code ? code : "");
    g_deadline = monotonic_seconds() + (expires_in > 0 ? expires_in : 0);
    g_visible = g_code[0] != '\0';
    if (g_mode != 4) g_mode = 1;
    g_drawn_remaining = -1;
    pthread_mutex_unlock(&g_lock);
}

void taiko_overlay_set_status(const char* text, int expires_in)
{
    pthread_mutex_lock(&g_lock);
    if (g_mode >= 3) {
        pthread_mutex_unlock(&g_lock);
        return;
    }
    snprintf(g_status, sizeof(g_status), "%s", text ? text : "");
    g_deadline = monotonic_seconds() + (expires_in > 0 ? expires_in : 0);
    g_visible = g_status[0] != '\0';
    g_mode = 2;
    g_drawn_remaining = -1;
    pthread_mutex_unlock(&g_lock);
}

void taiko_overlay_show_entry_menu(int selection)
{
    pthread_mutex_lock(&g_lock);
    g_host_selection = selection != 0;
    g_mode = 3;
    g_visible = 1;
    g_deadline = 0;
    g_drawn_remaining = -1;
    ++g_version;
    pthread_mutex_unlock(&g_lock);
}

void taiko_overlay_show_baid_wait(void)
{
    pthread_mutex_lock(&g_lock);
    g_mode = 4;
    g_visible = 1;
    g_drawn_remaining = -1;
    ++g_version;
    pthread_mutex_unlock(&g_lock);
}

void taiko_overlay_show_entry_progress(const char* player_name)
{
    pthread_mutex_lock(&g_lock);
    snprintf(g_player_name, sizeof(g_player_name), "%s",
             player_name && player_name[0] ? player_name : "P1");
    g_mode = 6;
    g_visible = 1;
    g_deadline = 0;
    g_drawn_remaining = -1;
    ++g_version;
    pthread_mutex_unlock(&g_lock);
}

void taiko_overlay_show_song_select(const char* player_name)
{
    pthread_mutex_lock(&g_lock);
    snprintf(g_player_name, sizeof(g_player_name), "%s",
             player_name && player_name[0] ? player_name : "P1");
    g_song_match_total = 0;
    g_song_catalog_total = 0;
    snprintf(g_song_category, sizeof(g_song_category), "ALL SONGS");
    g_song_category_index = 0;
    g_song_category_total = 1;
    g_song_row_count = 0;
    g_song_query[0] = '\0';
    g_song_search_active = 0;
    g_song_browser_level = TAIKO_OVERLAY_BROWSER_CATEGORIES;
    g_song_selection_is_exit = 0;
    g_mode = 5;
    g_visible = 1;
    g_deadline = 0;
    g_drawn_remaining = -1;
    ++g_version;
    pthread_mutex_unlock(&g_lock);
}

void taiko_overlay_show_song_browser(const char* player_name,
                                     const char* music_id,
                                     const char* title,
                                     const char* genre,
                                     uint32_t unique_id,
                                     unsigned index,
                                     unsigned match_total,
                                     unsigned catalog_total,
                                     const char* category,
                                     unsigned category_index,
                                     unsigned category_total,
                                     const char* difficulty,
                                     uint8_t difficulty_mask,
                                     const char* query,
                                     int search_active,
                                     int browser_level,
                                     int selection_is_exit,
                                     const taiko_overlay_song_row* rows,
                                     unsigned row_count)
{
    pthread_mutex_lock(&g_lock);
    snprintf(g_player_name, sizeof(g_player_name), "%s",
             player_name && player_name[0] ? player_name : "P1");
    snprintf(g_song_id, sizeof(g_song_id), "%s", music_id ? music_id : "");
    snprintf(g_song_title, sizeof(g_song_title), "%s", title ? title : "");
    snprintf(g_song_genre, sizeof(g_song_genre), "%s", genre ? genre : "");
    snprintf(g_song_difficulty, sizeof(g_song_difficulty), "%s",
             difficulty ? difficulty : "?");
    g_song_unique_id = unique_id;
    g_song_index = index;
    g_song_match_total = match_total;
    g_song_catalog_total = catalog_total;
    snprintf(g_song_category, sizeof(g_song_category), "%s",
             category ? category : "ALL SONGS");
    g_song_category_index = category_index;
    g_song_category_total = category_total;
    g_song_difficulty_mask = difficulty_mask;
    snprintf(g_song_query, sizeof(g_song_query), "%s", query ? query : "");
    g_song_search_active = search_active != 0;
    g_song_browser_level = browser_level;
    g_song_selection_is_exit = selection_is_exit != 0;
    g_song_row_count = row_count < TAIKO_OVERLAY_SONG_ROW_COUNT
        ? row_count : TAIKO_OVERLAY_SONG_ROW_COUNT;
    for (unsigned row = 0; row < g_song_row_count; ++row) {
        snprintf(g_song_rows[row].title, sizeof(g_song_rows[row].title), "%s",
                 rows && rows[row].title ? rows[row].title : "");
        snprintf(g_song_rows[row].genre, sizeof(g_song_rows[row].genre), "%s",
                 rows && rows[row].genre ? rows[row].genre : "");
        g_song_rows[row].catalog_index = rows ? rows[row].catalog_index : 0;
        g_song_rows[row].selected = rows && rows[row].selected;
        g_song_rows[row].kind = rows ? rows[row].kind
                                    : TAIKO_OVERLAY_ROW_SONG;
    }
    g_mode = 5;
    g_visible = 1;
    g_deadline = 0;
    g_drawn_remaining = -1;
    ++g_version;
    pthread_mutex_unlock(&g_lock);
}

void taiko_overlay_hide_host_screen(void)
{
    pthread_mutex_lock(&g_lock);
    if (g_mode >= 3) {
        g_mode = 0;
        g_visible = 0;
        g_code[0] = '\0';
        ++g_version;
    }
    pthread_mutex_unlock(&g_lock);
}

void taiko_overlay_clear(void)
{
    pthread_mutex_lock(&g_lock);
    if (g_mode >= 3) {
        if (g_code[0]) {
            g_code[0] = '\0';
            g_drawn_remaining = -1;
            ++g_version;
        }
        pthread_mutex_unlock(&g_lock);
        return;
    }
    if (g_visible) ++g_version;
    g_visible = 0;
    g_mode = 0;
    g_code[0] = '\0';
    g_status[0] = '\0';
    pthread_mutex_unlock(&g_lock);
}

const uint32_t* taiko_overlay_frame(int* width, int* height, uint32_t* version)
{
    pthread_mutex_lock(&g_lock);

    int remaining = (int)(g_deadline - monotonic_seconds());
    if (remaining < 0) remaining = 0;
    if (g_mode == 4 && g_code[0] && remaining == 0) {
        g_code[0] = '\0';
        g_drawn_remaining = -1;
        ++g_version;
    } else if (g_visible && g_mode < 3 && remaining == 0) {
        g_visible = 0;
        ++g_version;
    }
    if (!g_visible || !font_ready()) {
        const uint32_t current = g_version;
        pthread_mutex_unlock(&g_lock);
        if (version) *version = current;
        return NULL;
    }
    if (remaining != g_drawn_remaining) render(remaining);

    if (width) *width = g_width;
    if (height) *height = g_height;
    if (version) *version = g_version;
    pthread_mutex_unlock(&g_lock);
    return g_pixels;
}
